// import { Button, VerticalBox } from "std-widgets.slint";
// import { Webview } from "../src/webview/webview.slint";
// export { WebviewLogic } from "../src/webview/webview.slint";
// export component AppWindow inherits Window {
//     callback close();

//     in-out property <int> counter: 42;
//     callback request-increase-value();

//     in-out property <string> name;
//     callback request-update-name();

//     VerticalBox {
//         HorizontalLayout {
//             padding: 8px;

//             Text {
//                 text: "click botton to close";
//             }

//             Button {
//                 text: "x";
//                 primary: true;
//                 width: 2%; // two percent of the screen width
//                 height: 2%;
//                 clicked => {
//                     root.close()
//                 }
//             }
//         }

//         Text {
//             text: "Counter: \{root.counter}";
//         }

//         Text {
//             text: "\{root.name}";
//         }

//         Button {
//             text: "Increase value";
//             clicked => {
//                 root.request-increase-value();
//             }
//         }

//         Button {
//             text: "Chage name";
//             clicked => {
//                 root.request-update-name();
//             }
//         }
//     }
// }



import {
    VerticalBox,
    HorizontalBox,
    Button,
    LineEdit,
} from "std-widgets.slint";

import { Webview } from "../src/webview/webview.slint";

export { WebviewLogic } from "../src/webview/webview.slint";
export { Palette } from "std-widgets.slint";

export component AppWindow inherits Window {
    preferred-width: 1224px;
    preferred-height: 768px;

    property <bool> is-mobile: Platform.os == OperatingSystemType.ios || Platform.os == OperatingSystemType.android;

    contextMenuArea := ContextMenuArea {
        Menu {
            MenuItem {
                title: "Back";
                activated => webview.back();
            }

            MenuItem {
                title: "Forward";
                activated => webview.forward();
            }

            MenuItem {
                title: "Reload";
                activated => webview.reload();
            }

            MenuItem {
                title: "Go";
                activated => webview.loadUrl(lineEdit.text);
            }
        }
    }

    VerticalBox {
        padding-left: root.safe-area-insets.left;
        padding-top: root.safe-area-insets.top;
        padding-right: root.safe-area-insets.right;
        padding-bottom: root.safe-area-insets.bottom;

        HorizontalBox {
            height: 50px;
            padding: 8px;
            spacing: 8px;

            if !root.is-mobile: Button {
                text: "Back";
                clicked => webview.back();
            }

            if !root.is-mobile: Button {
                text: "Forward";
                clicked => webview.forward();
            }

            if !root.is-mobile: Button {
                text: "Reload";
                clicked => webview.reload();
            }

            lineEdit := LineEdit {
                text: webview.current_url;
                horizontal-stretch: 1;
                accepted(url) => webview.loadUrl(lineEdit.text);
            }

            if !root.is-mobile: Button {
                text: "Go";
                clicked => webview.loadUrl(lineEdit.text);
            }

            if root.is-mobile: Button {
                text: "...";
                clicked => contextMenuArea.show({ x: self.absolute-position.x, y: self.absolute-position.y + self.height });
            }
        }

        Rectangle {
            webview := Webview {
                width: 100%;
                height: 100%;
                changed current_url => {
                    lineEdit.text = self.current_url;
                }
            }
        }
    }
}
